### ISSUE TITLE
Regressions introduced by BDN change

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/performance#1031]
https://pvscmdupload.blob.core.windows.net/reports/report_x64_release-3.1.1xx_Default_Windows1018362_dotnetcoresdk_Micro_2019-11-12.html

I have a report linked above that shows several places where we have regressions that came from the change in BDN that was introduced between the to commits in that report. There is also some other movement there, but any place where you see a shelf in the regressions is where we are seeing this behavior.

**Comment by DrewScoggins** [comment]
@adamsitnik @billwert @ooooolivia

**Comment by DrewScoggins** [comment]
Specifically, this does not seem to be related to the underlying movement in the core-sdk product, but seems to be from the change that was introduced in the performance repo by https://github.com/dotnet/performance/commit/562fa1bff395580e058f1d995270f506fa6ed127. This change went into effect between these two core-sdk builds.

**Comment by adamsitnik** [comment]
Is this regression stable? I mean something like `______/******` in the graphs? And reproducible locally?

I am asking because this particular update should not affect the reported results. If it does I can investigate it next week (tomorrow I am traveling for Mono Team Week and Update Conference to Prague)
