### ISSUE TITLE
No new benchmark results since April 8th

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#1764]
While searching for `FileStream` perf improvements that I was hoping to see from https://github.com/dotnet/runtime/pull/50166/ I've noticed that the Reporting System is missing data from the 9th and 10th of April. It seems that something stopped working on the 8th of April:

![obraz](https://user-images.githubusercontent.com/6011991/114268116-b78b4500-99ff-11eb-8ef1-e8eb6c5c5670.png)

From my initial observation, it looks that both Windows and Linux runs are affected.
I hope that it's not related to our FileStream changes :)

cc @DrewScoggins @billwert

**Comment by DrewScoggins** [comment]
We have not stopped collecting data, looking at the pipelines everything has still been running. This issue is because I switched to using AAD for authentication and while it worked fine when I tested it locally, when I pushed the changes to our Batch service it failed. I have rolled that back until I can figure out why this was the case, and started a run to get the data live again.

**Comment by adamsitnik** [comment]
@DrewScoggins thank! I confirm that the results are now visible in the Reporting System:

![obraz](https://user-images.githubusercontent.com/6011991/114537381-6c1ca500-9c52-11eb-9a0b-41c7cdef5633.png)

**Comment by danmoseley** [comment]
That's a pretty nice graph to look at.
