### ISSUE TITLE
Microbenchmark reporting comparision broken for WASM and Interpreter scenarios

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/performance#1830]
The microbenchmark reporting page still missing the daily/weekly/monthly comparison for Mono Interpreter and Mono WASM scenarios. We need this fixed asap to measure changes going in.

Had a brief discussion with @DrewScoggins a few weeks back,. This is still broken. Example : https://pvscmdupload.blob.core.windows.net/reports/05_31_2021/report_Daily_ca=ARM64_cb=refs-heads-main_co=Ubuntu1804ARM_cr=dotnetruntime_cc=CompliationMode=tiered-LLVM=false-MonoAOT=true-MonoInterpreter=false-RunKind=micro_mono_2021-05-31.html

See the Diff link, and see baseline comparison numbers, they are from almost a month ago.

**Comment by DrewScoggins** [comment]
There are two issues here. The first is related to the daily comparison alone. Because of the use of changepoint analysis we now require more points between comparison and baseline than we normally get for a daily comparison. In order to fix this I am going to continue generating daily, but use a two day look back window. This should resolve the empty Daily run issue, and should do it for all configurations.

The second issue was why the particular weekly runs for interpreter and WASM were showing up blank. This is something that I had already solved locally, don't remember what the issue was, and just had not deployed to our Azure Batch. I will get that done today, along with the other change, and we should start seeing the Daily changes immediately, and the Weekly change on Monday.

**Comment by DrewScoggins** [comment]
These changes have been pushed. I will verify over the next couple days that the changes worked and then I will close this issue.
