### ISSUE TITLE
MAUI Desktop: Plumb data through

### ISSUE THREAD

**Issue by sblom** [dotnet/performance#2489]
- [x] Ensure the Maui Desktop Scenario runs are copied to the Maui table
- [x] Pipe through the new Maui Desktop names and make sure the correct name matching filters are applied

**Comment by LoopedBard3** [comment]
Waiting on #2488 for finalization.

**Comment by LoopedBard3** [comment]
After getting the data into the PowerBI, it became clear that the build timestamp will not work correctly for the date as we use fairly stable sdks (release/6.0) that don't get updated often. For the time being, I switched to using the ingestion timestamp since we haven't been replicating things yet. The Maui version will also still work, but a different way to kind of get a Maui time vs sdk time is needed.
