### ISSUE TITLE
Make sure the .logs from Python script are uploaded as CI artifacts and the CI fails if exitCode != 0

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#274]

**Comment by adamsitnik** [comment]
@adiaaida I tried to fix it in #280 but I have failed.

It looks like we have not been uploading the logs for a while. Could you please make sure that we do?

Also I have a feeling that if the python script returns non zero code we don't fail.

**Comment by adiaaida** [comment]
Alex is working on getting MC to do the right thing again. MC is where our logs are being uploaded, for lack of a better word, for the python scripts. As far as I am aware, that’s about the best we can do.  I’ve asked before, but there isn’t a way for azdo to archive artifacts from a job on a helix machine. We would want to publish the artifacts elsewhere. Are there other logs?

Also, yes, right now we are passing everything despite non-zero python exit codes. That is due to a bug in helix that Alex has a PR out to fix

**Comment by adamsitnik** [comment]
I am ok with the logs being uploaded to MC. I hope that we won't need them very often. If it ever changes, we can come back to this conversation.

> That is due to a bug in helix that Alex has a PR out to fix

Thanks for the update!

**Comment by adamsitnik** [comment]
Fixed by #305
