### ISSUE TITLE
Performance repo test runs are being uploaded with conflicting branch name

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2949]
Performance repo test runs that come from test branches are being uploaded with the branch of the channel_map channel used to download dotnet. This is causing test runs from my MoveMauiiOSMobile branch to parkerbibus/MoveMobileiOSMauiScenarios branch to show up as an 8.0 branch run. This does not occur in the runtime repo as we explicitly pass in the branch being used from Azdo. While we don't often run internal tests, any mobile updates need to be tested internally and will continue to contribute to this issue. Ideas for how to solve this would be greatly appreciated.

**Comment by LoopedBard3** [comment]
If we were to add two new fields, say RunPerfRepo and RunPerfRepoBranch to match the already present RunPerfRepoGitHash, would there be anything we would need to keep in mind before ingesting the results into ADX or Table Storage? I kind of assume that ADX would be resilient to this change, but am not sure about the Table Storage. Any insight you may have off the top of your head would be appreciated @caaavik-msft

**Comment by caaavik-msft** [comment]
I think the biggest impact is on the trend key, we probably want to include these two fields in the trend key so that they are treated as different trends. Perhaps what we could do is if the RunPerfRepo = dotnet/performance and the RunPerfRepoBranch = main, then we don't need to include them in the trend key, thus all the existing trend keys will remain the same and only runs with different perf repos or perf repo branch will use a different trend key.

I also think we need to double check if having a RunPerfRepo field is even needed, since I can't think of any scenario where that value won't be dotnet/performance.

As for ADX, it will be resilient to this change but by default it won't create columns in the Measurements table for the new fields, I would need to alter the import functions to add support for them. We can do this altering step after we have added the new fields, so no need to get it ready beforehand.

As for the table storage, I think it will also be resilient, we would just need to modify the copier azure function jobs to propagate those new fields into the schema for the relevant table entities. And then similarly update the report generation to read those new fields.

All in all, I think there is little risk in us adding these new fields to the perf lab jsons, then we can just identify all the other places that consume the json and update them to read the fields.
