### ISSUE TITLE
Benchmark NA results being inserted as 0 to history graphs

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#3121]
Found in https://github.com/dotnet/perf-autofiling-issues/issues/19719, some tests were erroring out and returning NA for each of the benchmark values. However, the NA values made their way into the allTestHistory graphs as 0 showing popping up as an improvement. NA values should not be included in the graphs so the best place to filter out NA values needs to be found.

**Comment by LoopedBard3** [comment]
fyi @DrewScoggins, please let me know if you have any specific insight that may help with this.

**Comment by DrewScoggins** [comment]
It looks like the culprit is here,https://github.com/dotnet/BenchmarkDotNet/blob/fd2639ff7b9e8353bb48c0eb6668c8bf32d19792/src/BenchmarkDotNet/Toolchains/MonoWasm/WasmExecutor.cs#L105. It looks like we are not doing any validation on the execution, so when we later look  to see if an error happened in this test we don't see one and create an empty `perf-lab-report.json`. It looks like @adamsitnik refactored this stuff a while back. Also add @radical who will likely have some input on what we want to do.

**Comment by radical** [comment]
Also, generating a `xunit/vstest` style test results xml with the *failed* benchmarks would be extremely helpful. Right now, you have to grep through the console log to find these. With the results xml, IIUC, the failures can show up in azdo.

**Comment by LoopedBard3** [comment]
This has been fixed since around 10/2023 as we no longer add test data to our tables if there are no results to add. If it is found that this is not fixed, either open a new issue or reopen this one. Closing.
