### ISSUE TITLE
Support for Outerloop benchmarks

### ISSUE THREAD

**Issue by krwq** [dotnet/performance#545]
Certain benchmarks do not need to run as part of every perf run and only need to run as part of making explicit changes in corefx. Such benchmarks should not have limit on number of test cases.

## Details

Currently benchmarks have [artifical limit of number of test cases per benchmark](https://github.com/dotnet/performance/blob/master/src/harness/BenchmarkDotNet.Extensions/TooManyTestCasesValidator.cs#L16) of 16.

in certain scenarios this limit is not justified (specifically when test cases don't need to run as part of every perf run which would be proposed outerloop).

I.e. JSON has multiple pieces of code which do similar things but code is split out for perf reasons. I.e. comment parsing code:
- comment can be single or multi-line
- payload can be multi- or single- segment (code is different for these cases as well)
- comment can be skipped or parsed
- comment can be long or short
- multi segment code have different perf characteristics depending i there are multiple segments or little segments

these permutations alone already give more than 16 test cases. Those tests only need to run when there are changes to comment parsing and do not need to run as part of every run.

Ideal solution would be marking these tests as OuterLoop and then don't run them by default and at the same time remove artifical limit of number of test cases on such benchmarks.

Possible implementation could be adding `[BenchmarkCategory.OuterLoop]` which would skip them for full runs but not skip them when using `--filter` directly.

cc: @adamsitnik

**Comment by billwert** [comment]
I'm torn about this. In general I'm not in favor of having code in the repo that isn't being run on some cadence - it just invites debt. (Though in this case the code would at least be building.) This needs some careful thinking around pros/cons before we decide to do it.

Looking at your list above, for example. What you're really doing is using the microbenchmark suite as a profiler. Given how easy it is to collect a profile (particularly with BDN) is it worth it to have dead tests laying around for the unlikely case that one of these things regresses?

**Comment by adamsitnik** [comment]
Another good example are the `Enum` benchmarks proposed in https://github.com/dotnet/performance/pull/237 They test almost every possible usage of enums (which is good) but on the other hand, they take most probably 15 or so minutes to run. There is a very little chance that we are going to regress the `Enum` but if we don't measure that periodically we can't tell if there is a regression or not.

So maybe instead of `OuterLoop` we should introduce a concept of priority categories?

Example: everything is Priority0 by default, but benchmarks that belong to Priority1 category are executed only once a week or so?

**Comment by krwq** [comment]
I like @adamsitnik's idea, I'd name the priorities though, i.e.:
- inner loop (pri 0)
- daily (pri 1)
- weekly (pri 2)
- monthly (pri 3)
