### ISSUE TITLE
benchmarks\real-world\Microsoft.ML.Benchmarks fails with private CoreRun.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/performance#894]
Repro steps:
1. goto performance\src\benchmarks\real-world\Microsoft.ML.Benchmarks
2. run  `dotnet.exe run --framework netcoreapp5.0 -c Release -- --filter *TrainSentiment* --coreRun "E:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe"` where CoreRun is build from the current master,
the command should fail with: 
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Unable to load DLL 'CpuMathNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
```
3. run without ` --coreRun` works fine;
4. run some others ML benchmarks with CoreRun works fine (`*HashScalar*`);

There are many issues about `CpuMathNative.dll` in machine learning repo, but they look irrelevant. 

Also, ML.Net doesn't use this library from 1.4 (this repo uses 0.1).

**Comment by adamsitnik** [comment]
@sandreenko thanks for a great bug report!

@najeeb-kazmi @eerhardt should we just update the version of ML.NET? We are currently using `0.10.0`, I can see that `1.4.0-preview` has a dependency to `Microsoft.ML.CpuMath` which targets not only .NET Standard (with the problematic native dependency) but also `netcoreapp3.0` which uses new managed APIs to do the vector math?

Also, are we going to ship stable version today|tomorrow as part of the .NET Conf?

**Comment by eerhardt** [comment]
The issue as far as I can tell is that no one is copying the native assembly `CpuMathNative` to the output folder. `corerun` is going to need that assembly in the app's directory, as I understand that is the only place it looks for it. Note that `dotnet.exe` doesn't need this, because it can be probed using the `.deps.json` file.

We can update the version of ML.NET if we want. Just note that it will require code changes in the tests, and will probably change the output metrics since the current build is ~8 months old.

If we use `1.4.0-preview` on `netcoreapp3.0+`, then we will no longer need to load the `CpuMathNative` assembly anymore, since it now uses the C# hardware intrinsics APIs. Again note that changes to the output metrics will happen here as well, since before we were only using SSE, and the new C# code will use AVX when available.

> Also, are we going to ship stable version today|tomorrow as part of the .NET Conf?

No, the current plan is to ship a stable `1.4` in a few weeks/months when the new image tasks are considered stable.

**Comment by sandreenko** [comment]
> The issue as far as I can tell is that no one is copying the native assembly CpuMathNative to the output folder. corerun is going to need that assembly in the app's directory, as I understand that is the only place it looks for it. Note that dotnet.exe doesn't need this, because it can be probed using the .deps.json file.

Thanks, I found `CpuMathNative.dll` in `C:\Users\*\.nuget\packages\microsoft.ml.cpumath\0.10.0\runtimes\win-x64\native\`, copied that to CoreRun folder and it worked.

**Comment by danmosemsft** [comment]
As I see it, we have ML.NET in this repo in order that we don't regress them, not to help them measure their own performance - they have more interesting scenarios and configurations for that. So presumably the netcoreapp3.0 version is the only one we need - it is the most interesting - and if it happens to be easiest because it drops the dependency on cpumathnative.dll, more's the better.

**Comment by eerhardt** [comment]
> we have ML.NET in this repo in order that we don't regress them

What I am saying above is that if we upgrade the ML.NET version in this repo, then we can no longer compare the new results with any results we've gotten in the past. If we are not concerned with that, then I am fine with upgrading the version.

> because it drops the dependency on cpumathnative.dll, more's the better.

It doesn't fix the underlying issue though, which is that the native dependencies are not being copied/loaded correctly. Just because this 1 native dependency is no longer needed, it doesn't mean that more native dependencies won't be needed. For example, `FastTreeNative` or anything that references MKL.

**Comment by sandreenko** [comment]
> What I am saying above is that if we upgrade the ML.NET version in this repo, then we can no longer compare the new results with any results we've gotten in the past. If we are not concerned with that, then I am fine with upgrading the version.

If the updated ML.Net lib shows better performance and we see it in benchview then it is good, why would we want to compare results after that with any results from the past? If the change shows a regression then it should be investigated, no?

From the jit perspective, I would like to have one place with ML benchmarks that I can run with private CoreCLR and that performance changes are "actual" (mean that users will see them if they install new CoreCLR and use new ML.Net), it is not interesting to improve Jit performance for ML.Net version that nobody uses already.

**Comment by adamsitnik** [comment]
> Just because this 1 native dependency is no longer needed, it doesn't mean that more native dependencies won't be needed

I did not know that ML.NET has more native dependencies, I was hoping that simple version update would fix it. BDN tracks this issue in https://github.com/dotnet/BenchmarkDotNet/issues/946 I hope that we can find a clean solution to this problem.

**Comment by adamsitnik** [comment]
> If the updated ML.Net lib shows better performance and we see it in benchview then it is good, why would we want to compare results after that with any results from the past? If the change shows a regression then it should be investigated, no?

The purpose of this repo is to make sure the .NET Core is not regressing the performance. With a hardcoded version number of ML.NET we make sure that if given benchmark takes longer to run it means that .NET Core has regressed ML.NET. This is why we have avoided more frequent updates. We plan to change it soon: https://github.com/dotnet/performance/issues/896

**Comment by BruceForstall** [comment]
If a newer version of ML.NET is now using the C# hardware intrinsic APIs, and not native code, we definitely want that, so we can measure the JIT performance of those.

**Comment by BruceForstall** [comment]
It appears that changing the hard-coded ML.NET version from `0.10.0` to `1.4.0-preview2` doesn't work, due to API changes. Perhaps someone who knows this area better (@najeeb-kazmi who created the test originally?) could fix it to work with the latest version?

There's also the questions about whether a second copy of the ML.NET benchmarks should be added, so there is one for the current `0.10.0` version, and one for the new `1.4.0-preview2` version. Then, after running both for a while, the older one could be retired. Perhaps that would allay concerns of missing out on the continuing trend tracking?

This is all related to https://github.com/dotnet/performance/issues/896. cc @billwert @brianrob @sandreenko

**Comment by brianrob** [comment]
I think having additional JIT coverage here absolutely seems interesting.  I do wonder if we just add a new version with new benchmarks and keep the old one for some unspecified period of time.  This allows us to keep the history and at the same time increase coverage.  I think that choosing to drop coverage for the old version can be a separate decision.
