### ISSUE TITLE
Create a plan for tracking moving product builds of non-platform libraries/tools

### ISSUE THREAD

**Issue by billwert** [dotnet/performance#896]
Currently we run ML.NET and Roslyn benchmarks in this repo. They use pinned versions of those products and test against live .NET Core bits. This is a great defense mechanism for ensuring future .NET Core products don't have regressions. It does not help us track the performance of ML.NET and Roslyn as they change, however. We'd like to do that as well.

The challenge is that in a given perf run we'd like there to be a single variable. Moving both the underlying .NET Core version as well as the library version makes it very hard to reason about what caused a regression. This is complicated by the fact that it is reasonable to assume that future versions of libraries and tools will take dependencies on new .NET Core features in prerelased versions. We can't expect a given Roslyn build to just work on the previously RTMed .NET Core.

We need a scheme that allows for:

* Rolling forward the non-platform bits frequently
* Pinning a .NET Core platform version as long as possible
* Has a mechanism for moving the pinned version with fixed versions of the other libraries

There may be other considerations but those are the critical ones to me.

**Comment by BruceForstall** [comment]
A specific example: based on the discussion in https://github.com/dotnet/performance/issues/894, ML.NET in this repo is 0.10.0, which is quite old compared to the current version, 1.4.0-preview2 (https://www.nuget.org/packages/Microsoft.ML/). In particular, it sounds like one important difference is that the current version uses managed SIMD / hardware intrinsics instructions instead of P/Invoke to a native library for these calculations. It's important to the JIT team, at least, to have these newer implementations be in the benchmark suite.

**Comment by adamsitnik** [comment]
One of the reasons why we did not update ML.NET version for a while was the fact that it was very frequently changing the public API. Since ML.NET 1.0 no breaking changes were introduced. 

ML.NET has it's own copy of the benchmarks, which are kept up-to-date. To update, we could just copy the source code from https://github.com/dotnet/machinelearning/tree/master/test/Microsoft.ML.Benchmarks

**Comment by adamsitnik** [comment]
Maybe we could have two jobs defined for ML.NET and Roslyn benchmarks: one using hardcoded and one latest version. I could extend the `.yml` micro-benchmark template with something optional like:

```yml
      versions: 
        - hardcoded
        - latest
```

And handle it properly from the MSBuild level using some Env Vars and conditions:

```xml
  <ItemGroup>
    <PackageReference Condition="'$(LibVersion)' == 'Hardcoded' Include="ML.NET" Version="1.4" />
    <PackageReference Condition="'$(LibVersion)' == 'Latest' Include="ML.NET" Version="1.*" />
  </ItemGroup>
```

I've used the asterisk here because ML.NET does not publish the packages using Maestro. So we don't know the exact latest version (however this information is available for Roslyn)

Then the remaining problem would be how to differentiate the results in the Reporting System? 

The disadvantage of such solution would be to run the benchmarks twice, however both ML.NET and Roslyn have just a few benchmarks so it should not be an issue.

@DrewScoggins @billwert what do you think?

**Comment by DrewScoggins** [comment]
The main problem I see is that this does not solve the two variables moving porblem. We could still end up in a situation where we see a regression, but cannot say if that came from the runtime changing or ML.NET.

From a reporting system stand point we would probably want to split these runs out. That should allow us to encode the information that we would need to differentiate between runs that are testing the runtime, the fixed ML.NET version, and those that are testing the library, the fixed runtime version.

**Comment by DrewScoggins** [comment]
I wanted to add a few more points to clarify. I think that this idea is a good start for how we can move to having a hard coded and a moving version for ML.NET, but we also need to pair it with the machinery to lock to a certain version of .NET as well. So in the case were we are always taking a new version of ML.NET we should fix on the current released version of .NET so that we can ensure that when we see a change we know what is causing that change.

Also to clarify more on the reporting side we will need to answer how we decide what is the moving variable for these runs. Typically, we just use new builds out of a repo and that forms the builds over time that we can compare and trend. Since we would be locking the version of .NET we would have to find use the ML.NET version as the "build" that we use for tracking over time. Solving this issue will be important as I suspect we will see many cases like this in the future where we want to test libraries that are part of the .NET ecosystem, but not part of the main shipping vehicle of core-sdk.

**Comment by eerhardt** [comment]
In the context of ML.NET updating versus .NET runtime updating, I like the idea of having 2 separate "pipelines". Each pipeline has one library that is "constantly updated" and the other library is on its "last stable release" version.

So, for example, today we have ML.NET `1.4` and .NET Core `3.0` as the last stable releases of each. So we would have 2 pipelines:

1. ML.NET constantly updating, while .NET Core runtime stays on `3.0`.
2. .NET Core runtime constantly updating, while ML.NET stays on `1.4`.

Then, the way we solve the problem we currently have - the version of ML.NET used in the perf runs is almost a year old - we update each "last stable release" periodically as a new release comes out.

Today we would have:

1. `ML.NET build from last night on top of .NET Core 3.0.`

And when .NET Core `3.1` shipped, we would update this pipeline to:

1. `ML.NET build from last night on top of .NET Core 3.1.`

Likewise we would also have:

2. `ML.NET 1.4 on top of .NET core build from last night`

And when ML.NET `1.5` is shipped, we would update this pipeline to:

2. `ML.NET 1.5 on top of .NET core build from last night`
